site_name: Kotlin
site_url: https://bpaterna.github.io/kotlin/
site_author: Begoña Paterna
theme:
  name: material
  language: es
  palette:
    scheme: default
    primary: purple
  features:
    - content.code.copy
    - content.tabs.link
    - navigation.instant
    - navigation.top
    - navigation.sections
    - search.highlight
    - search.suggest
    - toc.integrate
nav:
  - 1. Entorno de desarrollo: kotlin01.md
  - 2. Variables y tipos de datos: kotlin02.md
  - 3. Entrada y salida estándar: kotlin03.md
  - 4. Estructuras de control: kotlin04.md
  - 5. Funciones: kotlin05.md
  - 6. Estructuras de datos: kotlin06.md
  - 7. Programación Orientada a Objetos: kotlin07.md
  - 8. Programación funcional y expresiones Lambda: kotlin08.md
  - 9. Gestión de errores: kotlin09.md
markdown_extensions:
  - attr_list
  - admonition
  - footnotes
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
extra_css:
  - stylesheets/extra.css
use_directory_urls: false
